version: '3.5'
services:
  soundchat-mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@321
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: soundchat_dev
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - "3306"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - soundchat-mysql:/var/lib/mysql

  soundchat-redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]

  soundchat-server:
    image: huypq/soundchat_soundchat-server:v1
    depends_on:
      - soundchat-mysql
      - soundchat-redis
    environment:
       FLASK_ENV: production
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "8000:8000"

  celery-worker:
    image: huypq/soundchat_celery-worker:v1
    depends_on:
      - soundchat-redis
    environment:
      FLASK_ENV: production
    deploy:
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

volumes:
  soundchat-mysql: