version: '3.5'
services:
  soundchat-mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@321
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: soundchat_dev
    restart: unless-stopped
    ports:
      - "33061:3306"
    expose:
      - '3306'
    volumes:
      - soundchat-mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: soundchat-mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: soundchat_admin
    ports:
      - 9000:80
    depends_on:
      - soundchat-mysql

  soundchat-redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  soundchat-server:
    build:
      context: ./soundchat_server
      dockerfile: Dockerfile
    depends_on:
      - soundchat-mysql
      - soundchat-redis
    environment:
       FLASK_ENV: production
    ports:
      - "8000:8000"

  celery-worker:
    build:
      context: ./soundchat-server
      dockerfile: CeleryWorkerDockerfile
    depends_on:
      - soundchat-redis
    environment:
      FLASK_ENV: production

volumes:
  soundchat-mysql: