"""empty message

Revision ID: 6254a3fc92c6
Revises: 
Create Date: 2019-05-28 01:19:30.984106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6254a3fc92c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###'
    op.create_table('users',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('password_salt', sa.String(length=16), nullable=True),
    sa.Column('online', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email')
    )
    op.create_table('messages',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('room_participants',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('video_status', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'room_id', name=op.f('pk_room_participants'))
    )
    op.create_table('rooms',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('current_video', sa.Integer(), nullable=True),
    sa.Column('video_time', sa.Float(), nullable=True),
    sa.Column('fingerprint', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    op.create_table('videos',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('total_vote', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos'))
    )
    op.create_table('votes',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_votes'))
    )
    op.create_foreign_key('fk_messages_room_id_rooms', 'messages', 'rooms', ['room_id'], ['id'], ),
    op.create_foreign_key('fk_messages_user_id_users', 'messages', 'users', ['user_id'], ['id']),
    op.create_foreign_key('fk_room_participants_room_id_rooms', 'room_participants', 'rooms', ['room_id'], ['id']),
    op.create_foreign_key('fk_room_participants_user_id_users', 'room_participants', 'users', ['user_id'], ['id']),
    op.create_foreign_key('fk_rooms_creator_id_users', 'rooms', 'users', ['creator_id'], ['id']),
    op.create_foreign_key('fk_rooms_current_video_videos', 'rooms', 'videos', ['current_video'], ['id']),
    op.create_foreign_key('fk_videos_creator_id_users', 'videos', 'users', ['creator_id'], ['id']),
    op.create_foreign_key('fk_videos_room_id_rooms', 'videos', 'rooms', ['room_id'], ['id']),
    op.create_foreign_key('fk_votes_user_id_users', 'votes', 'users', ['user_id'], ['id']),
    op.create_foreign_key('fk_votes_video_id_videos', 'votes', 'videos', ['video_id'], ['id']),

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('videos')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('room_participants')
    op.drop_table('messages')
    # ### end Alembic commands ###
