"""empty message

Revision ID: 753d7d197a3e
Revises: 
Create Date: 2019-04-24 20:57:59.977662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753d7d197a3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('total_vote', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_media_creator_id_user')),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_media_room_id_room')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_table('message',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_message_room_id_room')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_message_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_table('room',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('current_media', sa.Integer(), nullable=True),
    sa.Column('media_time', sa.Float(), nullable=True),
    sa.Column('room_fingerprint', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_room_creator_id_user')),
    sa.ForeignKeyConstraint(['current_media'], ['media.id'], name=op.f('fk_room_current_media_media')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room'))
    )
    op.create_table('room_paticipant',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('media_status', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_room_paticipant_room_id_room')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_room_paticipant_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'room_id', name=op.f('pk_room_paticipant'))
    )
    op.create_table('room_playlist',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_room_playlist_media_id_media')),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_room_playlist_room_id_room')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_playlist'))
    )
    op.create_table('user',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('password_salt', sa.String(length=16), nullable=True),
    sa.Column('online', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email')
    )
    op.create_table('vote',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_vote_media_id_media')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_vote_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('user')
    op.drop_table('room_playlist')
    op.drop_table('room_paticipant')
    op.drop_table('room')
    op.drop_table('message')
    op.drop_table('media')
    # ### end Alembic commands ###
